version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t my-nginx:latest .
      - deploy:
          name: Push Docker image into hub.docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag my-nginx kkryvasov/my-nginx
            docker push kkryvasov/my-nginx


#step 2
#          name: Setup kubectl and trigger pods recreation
#          command: |
#            sudo apt-get install -y curl
#            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
#            chmod +x kubectl
#            echo $KUBECTL_CONF > kubeconfig
#            sed -ie "s/THIS_STRING_IS_REPLACED_DURING_BUILD/$(date)/g" nginx_deployment.yaml
#            env KUBECONFIG=kubeconfig PATH=$PATH:. kubectl apply --force -f nginx_deployment.yaml
