version: 2
jobs:
  build_image:
    docker:
#      - image: kkryvasov/my-nginx:kubectl
#        auth:
#          username: $DOCKER_USER
#          password: $DOCKER_PASS
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t my-nginx:latest .
      - run:
          name: Push Docker image into hub.docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag my-nginx kkryvasov/my-nginx
            docker push kkryvasov/my-nginx
  build:
    docker:
      - image: ubuntu 
    steps:
      - checkout
      - run:
          name: install kubectl
          command: |
             curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
             chmod +x kubectl
      - run:
          name: configure kubectl and trigger kube
          command: |
            sudo apt-get install -y curl
            gpg --output=kubeconfig --passphrase=$PASSPHRASE --decrypt config.gpg 
            sed -ie "s/THIS_STRING_IS_REPLACED_DURING_BUILD/$(date)/g" nginx_deployment.yaml
            env KUBECONFIG=kubeconfig PATH=$PATH:. kubectl apply --force -f nginx_deployment.yaml
workflows:
  version: 2
  main:
    jobs:
      - build
      - build_image:
          requires:
            - build
